apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-expresss
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-expresss
  template:
    metadata:
      labels:
        app: mongo-expresss
    spec:
      containers:
      - name: mongo-expresss
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key:  mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key:  mongo-root-username
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
              


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-expresss
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
